Traceback (most recent call last):
  File "/home/sabih/return/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/sabih/return/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/sabih/.local/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/sabih/return/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/sabih/return/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/home/sabih/return/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/sabih/return/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Code processig en filterig hier
# df_temp = df_WDI_all
# for x in range(1975, 2014):
#    st = str(x) + ' [YR' + str(x) + ']'
#    df_temp = df_temp.drop(st, axis=1)
# df_WDI_processed = df_temp
â‚¬ df_WDI_processed.to_csv('processed_data/WDI_2014-2024.csv', index=False)
------------------


[0;36m  Cell [0;32mIn[5], line 7[0;36m[0m
[0;31m    â‚¬ df_WDI_processed.to_csv('processed_data/WDI_2014-2024.csv', index=False)[0m
[0m    ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid character 'â‚¬' (U+20AC)


